import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home({ accommodationSuggestions }) {
  return (
    <>
      <Head>
        <title>Airbnb - Ferienwohnungen und Apartments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* Banner */}
      <main>
        <Hero />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const accommodationSuggestions = await fetch(
    "https://www.jsonkeeper.com/b/4G1G"
  ).then((res) => res.json());

  return {
    props: {
      accommodationSuggestions,
    },
  };
}
